version: '3'
services:
  app:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - app-volume:/usr/local/volume
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  app-volume: